# Generated by Django 2.1 on 2018-08-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180828_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_account',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
