# Generated by Django 2.1 on 2018-08-30 06:01

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_paypal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.accounts.fields.PhoneField(blank=True, max_length=20, null=True),
        ),
    ]
