# Generated by Django 2.1 on 2018-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180830_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_validated',
            field=models.BooleanField(default=False),
        ),
    ]
