# Generated by Django 2.1 on 2018-09-18 07:30

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    user = apps.get_model('accounts', 'User')
    for user in user.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_phone_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   editable=False,
                                   unique=True),
        ),


    ]
