version: '3'

services:
  db:
    image: mdillon/postgis:9.5-alpine
    ports:
    - 5432:5432

  redis:
    image: redis:3-alpine

  api:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    - redis
    environment:
      DATABASE_URL: postgis://postgres@db/postgres
      REDIS_URL: redis://redis
    ports:
    - 8000:8000

  celery:
    build: .
    command: celery -A config worker -B -l info
    depends_on:
    - db
    - redis
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://postgres:@db:5432/postgres
      BROKER_URL: redis://redis
      REDIS_URL: redis://redis
      C_FORCE_ROOT: "True"

