version: '3'

services:
  db:
    image: mdillon/postgis:9.5-alpine
    ports:
    - 5432:5432

  redis:
    image: redis:3-alpine

  api:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    depends_on:
    - db
    - redis
    ports:
    - 8000:8000
    env_file:
    - .env

  celery:
    build: .
    command: celery -A config worker -B -l info
    depends_on:
    - db
    - redis
    env_file:
    - .env
