# Generated by Django 2.1 on 2018-08-21 06:08
import os
import json
from django.db import migrations
from django.conf import settings


def forward_code(apps, schema_editor):
    City = apps.get_model('places', 'City')
    State = apps.get_model('places', 'State')

    data = json.loads(
        open(os.path.join(
            settings.BASE_DIR, 'apps', 'places',
            'migrations', 'cities.json')).read())

    for state_name in data:
        state = State.objects.create(name=state_name)
        for city_name in data[state_name]:
            City.objects.create(
                name=city_name,
                state=state)


def backward_code(apps, schema_editor):
    City = apps.get_model('places', 'City')
    State = apps.get_model('places', 'State')

    City.objects.all().delete()
    State.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_code, backward_code)
    ]
