# Generated by Django 2.1 on 2018-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
