# Generated by Django 2.1 on 2018-10-15 07:31

import apps.cars.upload_paths
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181005_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.cars.upload_paths.car_photo_path),
        ),
    ]
