# Generated by Django 2.1 on 2018-10-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20181005_0737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
