# Generated by Django 2.1 on 2018-10-30 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20181005_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=80)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category', models.CharField(choices=[('ts', 'Train station'), ('bs', 'Bus station'), ('a', 'Airport'), ('ep', 'Education place')], max_length=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.City')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='short_name',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
