# Generated by Django 2.1 on 2018-09-19 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '__first__'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_of_seats', models.PositiveSmallIntegerField(verbose_name='Available number of seats during ride')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='cars.Car')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.City')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payed', 'Payed'), ('canceled', 'Canceled'), ('succeed', 'Succeed'), ('failed', 'Failed')], default='created', max_length=10)),
                ('seats_count', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rides.Ride')),
            ],
        ),
        migrations.CreateModel(
            name='RideComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('considered', 'Considered'), ('confirmed', 'Confirmed'), ('disapproved', 'Disapproved')], default='new', max_length=10)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='rides.Ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.City')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.City')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.Ride')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ridebooking',
            unique_together={('ride', 'client')},
        ),
    ]
