# Generated by Django 2.1 on 2018-08-28 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridepoint',
            old_name='stop',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='end',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='stops',
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 28, 4, 48, 58, 614285, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.Ride'),
        ),
    ]
