# Generated by Django 2.1 on 2018-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='paypal_approval_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='paypal_payment_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridebooking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('payed', 'Payed'), ('canceled', 'Canceled'), ('succeed', 'Succeed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=10),
        ),
    ]
