# Generated by Django 2.1 on 2018-09-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20180920_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='paypal_approval_link',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='paypal_payment_id',
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='paypal_approval_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='paypal_payment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
