# Generated by Django 2.1 on 2018-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20180924_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='created', max_length=10),
        ),
    ]
