# Generated by Django 2.1 on 2018-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20180920_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('payed', 'Payed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='created', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='ridebooking',
            unique_together=set(),
        ),
    ]
