# Generated by Django 2.1 on 2018-09-18 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20180907_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridecomplaint',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 7, 28, 6, 262222, tzinfo=utc)),
        ),
    ]
