# Generated by Django 2.1 on 2018-09-18 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20180918_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridecomplaint',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 7, 30, 55, 8966, tzinfo=utc)),
        ),
    ]
