# Generated by Django 2.1 on 2018-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20181004_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
