# Generated by Django 2.1 on 2018-10-30 13:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20181030_1218'),
        ('rides', '0006_auto_20181005_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AddField(
            model_name='ride',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='place_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='place_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AddField(
            model_name='ridestop',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='number_of_seats',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Available number of seats during ride'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='ridestop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='places.City'),
        ),
    ]
