# Generated by Django 2.1 on 2018-09-03 13:46
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="Account activate",
        subject="Account activation",
        message="""
        <p>You're receiving this email because you need to finish activation process on {{ site_name }}.</p>
        <p>Please go to the following page to activate account:</p>
        <p><a href="{{ url }}">{{ url }}</a></p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="account_activate",
        is_html=True,)


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(load_mail_template),
        migrations.RunPython(clean_cache),
    ]
