# Generated by Django 2.1 on 2018-10-24 14:48
from django.core.management import call_command
from django.db import migrations


def initialize_dbmail_templates(apps, schema_editor):
    call_command('init_dbmail_templates')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(initialize_dbmail_templates)
    ]
