# Generated by Django 2.1 on 2018-09-03 14:16
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="Account confirmation",
        subject="{{ site_name }} | Your account has been successfully created and activated!",
        message="""
        <p>Your account has been created and is ready to use!</p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="account_confirmation",
        is_html=True,)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='account_confirmation'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0001_email_user_account_activation'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
