# Generated by Django 2.1 on 2018-09-03 14:22
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="Password reset",
        subject="{{ site_name }} | Password reset",
        message="""
        <p>You're receiving this email because you requested a password reset for your user account at {{ site_name }}.</p>
        <p>Please go to the following page and choose a new password:</p>
        <a href="{{ url }}">{{ url }}</a>
        <p>Your username, in case you've forgotten: <b>{{ user.get_username }}</b></p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="account_password_reset",
        is_html=True,)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='account_password_reset'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0002_email_user_account_confirmation'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
