# Generated by Django 2.1 on 2018-09-04 09:24
from dbmail.models import MailTemplate
from django.db import migrations


# TODO: Add link with search for the new ride
def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="The ride has been deleted",
        subject="{{ site_name }} | The ride {{ ride }} has been deleted",
        message="""
        <p>You're receiving this email because you booked ride has been deleted at {{ site_name }}.</p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="ride_has_been_deleted",
        is_html=True,)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='ride_has_been_deleted'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0003_email_user_account_password_reset'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
