# Generated by Django 2.1 on 2018-09-27 08:31

from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="New ride for ride request",
        subject="{{ site_name }} | You have a new ride suggest: {{ ride }}",
        message="""
        <p>You created a ride request {{ ride_request }}</p>
        <p>There is a ride for you:</p>
        <a href="{{ ride_url }}">{{ ride }}</a>
        """,
        slug="new_ride_for_ride_request",
        is_html=True,)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='new_ride_for_ride_request'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0006_email_new_ride_complaint'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
