# Generated by Django 2.1 on 2018-09-24 05:07
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="The ride_booking canceled (client)",
        subject="{{ site_name }} | Information about canceled ride {{ ride }}.",
        message="""
        <p>You're receiving this email because you cancel the ride booking</p>
        <p><b>There is an information about the ride:<b><br>
        <b>Car:</b> {{ ride.car }}<br>
        <b>Number of seats:</b> {{ ride.number_of_seats }}<br>
        <b>Description:</b> {{ ride.description }}<br>
        </p>
        <p>You can see the ride details <a href='{{ ride_detail }}'>here</a></p>
        <p>You payment will be refunded soon by PayPal.</p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="client_ride_booking_refunded",
        is_html=True,)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='client_ride_booking_refunded'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0010_email_ride_payout_to_owner'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
