# Generated by Django 2.1 on 2018-09-24 05:07
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="The ride_booking canceled (owner)",
        subject="The client canceled the booking for ride {{ booking.ride }}",
        message="""
        <p></p>
        <p><b>There is an information about the ride:<b><br>
        <b>Car:</b> {{ booking.ride.car }}<br>
        <b>Number of sits:</b> {{ booking.ride.number_of_sits }}<br>
        <b>Description:</b> {{ booking.ride.description }}<br
        </p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="owner_ride_booking_canceled",
        is_html=True,)


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0011_email_ride_client_ride_booking_refunded'),
    ]

    operations = [
        migrations.RunPython(load_mail_template),
        migrations.RunPython(clean_cache),
    ]
