# Generated by Django 2.1 on 2018-10-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0012_email_ride_owner_ride_booking_refunded'),
        ('dbmail_templates', '0009_email_driver_booking_ride'),
    ]

    operations = [
    ]
