# Generated by Django 2.1 on 2018-09-24 05:07
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="Rate the ride passengers",
        subject="{{ site_name }} | You can rate passengers from the ride {{ ride }}",
        message="""
        <p></p>
        <p>You can rate passengers from your ride, 
        by using this link: _______
        </p>
        <p>Thanks for using our site!</p>
        <p>The {{ site_name }} team</p>""",
        slug="ride_review_inform_driver",
        is_html=True)
    # TODO link!


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='ride_review_inform_driver'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0012_email_ride_owner_ride_booking_refunded'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
