# Generated by Django 2.1 on 2018-09-24 05:07
from dbmail.models import MailTemplate
from django.db import migrations


def load_mail_template(apps, schema_editor):
    MailTemplate.objects.create(
        name="Rate the ride",
        subject="{{ site_name }} | You can rate the ride {{ ride }}",
        message="""
            <p></p>
            <p>You can rate the ride {{ ride }} and driver 
            {{ driver.first_name }} {{ driver.last_name }}<br>
            <b>Date:</b> {{ ride_date_time }}<br>
            <b>Car:</b> {{ ride.car }}<br>
            <b>Number of seats:</b> {{ ride.number_of_seats }}<br>
            <b>Description:</b> {{ ride.description }}<br>
            Using this link: <a href='{{ review_url }}'>rate a ride.</a>
            </p>
            <p>Thanks for using our site!</p>
            <p>The {{ site_name }} team</p>""",
        slug="ride_review_inform_passenger",
        is_html=True)


def delete_mail_template(apps, schema_editor):
    MailTemplate.objects.filter(
        slug='ride_review_inform_passenger'
    ).delete()


def clean_cache(apps, schema_editor):
    from dbmail.models import MailTemplate, ApiKey

    MailTemplate.clean_cache()
    ApiKey.clean_cache()


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0013_email_ride_review_inform_driver'),
    ]

    operations = [
        migrations.RunPython(load_mail_template, delete_mail_template),
        migrations.RunPython(clean_cache, lambda apps, schema_editor: None),
    ]
