# Generated by Django 2.1 on 2018-10-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail_templates', '0013_merge_20181002_0748'),
        ('dbmail_templates', '0014_email_ride_review_inform_passenger'),
    ]

    operations = [
    ]
